In [2]:
!pip install numpy

In [3]:
import numpy as np
print(np.__version__)

2.2.3


In [8]:
# Create a nomral NumPy array
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [18]:
# Create an numpy array of size 3x4 filled wth zeros

arr2 = np.zeros((3,4), dtype=float)
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
# Create an numpy array of size 3x4 filled wth ones

arr3 = np.ones((3,4), dtype=int)
arr3

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
# Create an numpy array of size 3x4 filled wth 69

arr4 = np.full((3,4), 69)
arr4

array([[69, 69, 69, 69],
       [69, 69, 69, 69],
       [69, 69, 69, 69]])

In [24]:
# Create an numpy array of elements from 0 to 100, with an even spacing of 10

arr5 = np.arange(0, 100, 10)
arr5

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
# Create an numpy array of elements between 0 and 100, with an even gap of 4

arr6 = np.linspace(0, 100, 4)
arr6

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [34]:
# Create an numpy array of elements filled randomly of size 3x3

arr7 = np.random.random((3,3))
arr7

array([[0.45660071, 0.85950485, 0.30601569],
       [0.28704414, 0.4236545 , 0.55613665],
       [0.64014147, 0.34579946, 0.15779539]])

In [40]:
# Create an numpy array of elements filled with elem

arr8 = np.random.normal(10, 10,(3,4))
arr8

array([[31.34248433, 11.75899162, 24.61222402, 16.36365653],
       [13.27544937, 16.83265256,  8.04652426, -6.79691542],
       [ 1.56624409, 15.12594755, 17.01038723,  9.84349793]])

In [41]:
arr9 = np.random.randint(0, 10, (5,5))
arr9

array([[2, 7, 5, 7, 4],
       [1, 0, 0, 9, 7],
       [2, 6, 7, 0, 8],
       [3, 7, 5, 9, 9],
       [1, 9, 1, 3, 1]])

In [49]:
arr10 = np.eye(10)
arr10

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [51]:
arr11 = np.empty(10)
arr11

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])