In [1]:
!pip install numpy

In [5]:
import numpy as np
arr = np.random.randint(1, 20, size=(5,5))
print(arr)

arr[:, 2] = 1
print(arr)

[[12  3 14  1  5]
 [15  5 11 12 12]
 [16  3 18 15 19]
 [18  7 14  2 16]
 [ 8 13 17 11 14]]
[[12  3  1  1  5]
 [15  5  1 12 12]
 [16  3  1 15 19]
 [18  7  1  2 16]
 [ 8 13  1 11 14]]


In [11]:
arr2 = np.arange(1, 17).reshape((4,4))

np.fill_diagonal(arr2, 0)
print(arr2)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [13]:
arr3 = np.arange(1, 37).reshape((6,6))
print(arr3[2:5, 1:4])

[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [32]:
arr4 = np.random.randint(1,21, size=(5,5))
print(arr4)
for i in range(5):
    for j in range(5):
        if i == 0 or j == 0 or i == 4 or j == 4:
            print(arr4[i][j],end="\t\t")
        else:
            print("\t",end="\t" )
    print()

[[15 10 18  4  6]
 [16 11  7 10  4]
 [11 20 12 11  4]
 [ 3 12 19 13  4]
 [20  9 11  9 13]]
15		10		18		4		6		
16								4		
11								4		
3								4		
20		9		11		9		13		


In [35]:
arr5 = np.random.randint(1, 13, size=(3,4))
arr6 = np.random.randint(1, 13, size=(3,4))
print(arr5 - arr6)
print(arr5 + arr6)
print(arr5 * arr6)
print(arr5 / arr6)



[[ 6  3  3 -1]
 [-1 -2 -2 -1]
 [10 -6  9 -2]]
[[14  7 21  9]
 [ 9  6 20 15]
 [12 16 15  8]]
[[ 40  10 108  20]
 [ 20   8  99  56]
 [ 11  55  36  15]]
[[ 2.5         2.5         1.33333333  0.8       ]
 [ 0.8         0.5         0.81818182  0.875     ]
 [11.          0.45454545  4.          0.6       ]]


In [37]:
arr7 = np.random.randint(1,17, size=(4,4))
print(arr7)
print(arr7.sum(axis=0))
print(arr7.sum(axis=1))

[[ 3 16 16 12]
 [13  3  7  8]
 [ 9  4  4 14]
 [16 16  1  1]]
[41 39 28 35]
[47 31 31 34]


In [38]:
arr8 = np.random.randint(1, 26, size=(5,5))
print(f"Mean {arr8.mean()}")
print(f"Median {np.median(arr8)}")
print(f"Standard Deviation {np.std(arr8)}")
print(f"Variance {np.var(arr8)}")

Mean 11.76
Median 10.0
Standard Deviation 6.592601914267234
Variance 43.462399999999995


In [39]:
arr9 = np.arange(1, 10).reshape((3,3))
mean = np.mean(arr9)
std = np.std(arr9)
normalized_array = (arr9-mean)/std
print(normalized_array)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [40]:
arr10 = np.random.randint(1,10, size=(3,3))
row1 = np.random.randint(1,4, size=(3,))
print(arr10+row1)

[[11  6  6]
 [ 6  5  7]
 [ 8  3 10]]


In [50]:
arr11 = np.random.randint(1,100, size=(4,4))
col1 = np.random.randint(1,10, size=(4,))

print(arr11)
print(col1)
print(col1[:, np.newaxis])
print(arr11-col1[:, np.newaxis])

[[90 16  7 10]
 [30 87 44 74]
 [14 18 62 40]
 [99 24 12 72]]
[3 7 9 7]
[[3]
 [7]
 [9]
 [7]]
[[87 13  4  7]
 [23 80 37 67]
 [ 5  9 53 31]
 [92 17  5 65]]


In [51]:
arr12 = np.random.randint(1,100, size=(3,3))
print(np.linalg.det(arr12))
print(np.linalg.eigvals(arr12))
print(np.linalg.inv(arr12))

-30522.000000000015
[132.83924131 -24.29614914   9.45690784]
[[-0.00589739 -0.05297818  0.04629448]
 [-0.00897713  0.08046655 -0.04619619]
 [ 0.03852959 -0.02054256 -0.00245724]]


In [53]:
arr13 = np.random.randint(1,100, size=(2,3))
arr14 = np.random.randint(1,100, size=(3,2))

print(np.dot(arr13, arr14))

[[ 5161  6691]
 [ 7168 10522]]


In [60]:
arr15 = np.arange(1, 10).reshape(3,3)
print(arr15)
arr15.reshape(1,9)
arr15.reshape(9,1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [63]:
arr16 = np.random.randint(1,100, size=(5,5)).flatten()
arr16
arr16.reshape(5,5)

array([[85, 42, 51, 82, 35],
       [22, 38, 14, 21, 48],
       [10, 41, 19, 83, 55],
       [96, 84, 35, 50, 56],
       [87, 47, 44, 30, 90]])

In [71]:
arr17 = np.random.randint(1, 100, size=(5,5))
arr17
print(arr17)
print(arr17[0, 0], arr17[0, -1], arr17[-1, 0], arr17[-1, -1])

[[69 77 40 60 98]
 [96 82 79 97 80]
 [63 54 15 83 67]
 [40 48 37 45 75]
 [39 40 48 14 28]]
69 98 39 28


In [78]:
arr18 = np.random.randint(1,100, size=(4,4))
arr18[arr18 > 10] = 10
print(arr18)

[[10  7 10 10]
 [10 10 10 10]
 [10 10 10  6]
 [10 10 10 10]]


In [83]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([("Hardik", 81, 70.5), ("Richard", 20, 78.9)], dtype=data_type)

data = np.sort(data, order="age")
print(data)


[('Richard', 20, 78.9) ('Hardik', 81, 70.5)]


In [86]:
arr19 = np.random.randint(1, 100, size=(4,4))
print(arr19)
arr19[arr19 > 10] = 0
print(arr19)
print(arr19[arr19 != 0].sum())

[[79 51 19 32]
 [11 94 78 79]
 [23 99 75 54]
 [ 4 68 69  1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [4 0 0 1]]
5


In [87]:
arr19 = np.random.randint(1, 100, size=(3,3))
print(arr19)
np.fill_diagonal(arr19, 0)
print(arr19)
m = (arr19[arr19 != 0].mean())
print(m)
np.fill_diagonal(arr19, m)
print(arr19)


[[59 18 95]
 [38  7 34]
 [63 45 27]]
[[ 0 18 95]
 [38  0 34]
 [63 45  0]]
48.833333333333336
[[48 18 95]
 [38 48 34]
 [63 45 48]]
